# -*- coding: utf-8 -*-
"""BondDuration_File.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/ZiyueLiu-zl3472/week5/blob/main/BondDuration_File.ipynb
"""

import numpy as np

def getBondDuration(y, face, couponRate, m, ppy=1):
  years=np.arange(1,m*ppy+1)/ppy #you divide by ppy to reflect the real semi-annual payments every half year
  df=1/(1+y/ppy)
  dfs=df**np.arange(1,m*ppy+1)
  cpn=couponRate*face/ppy
  cf=dfs*cpn
  w=cf*years

  sumCF=cf.sum()+dfs[-1]*face
  sumW=w.sum()+dfs[-1]*face*years[-1]

  BondDuration=sumW/sumCF

  return(BondDuration)

# Test values

y = 0.03
face = 2000000
couponRate = 0.04
m = 10
ppy = 1
ppy = 2

getBondDuration(y, face, couponRate, m, ppy)